A. Menarini	        Thailand
ACE NUTRITION SDN BHD   Malaysia
ace nutrition sdn.bhd	Malaysia
Acebiopharm	        South Korea





A&B Flavors	                Switzerland
AAKRUSHI VENTURES LLP	        India
AB World Foods Asia Ltd	        Thailand
Abdul Salam Distributors	Sri Lanka